{% set name = "quantecon" %}
{% set version = "0.8.2" %}

package:
  name: quantecon
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quantecon-{{ version }}.tar.gz
  sha256: 4380922cb993d5a277ac32f94a64659fe22586e1bc5758d44921308dc656e8f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.5,<4
  run:
    - numba >=0.49.0
    - numpy >=1.17.0
    - python >={{ python_min }}
    - requests
    - scipy >=1.5.0
    - sympy

test:
  imports:
    - quantecon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/QuantEcon/QuantEcon.py
  license: BSD-3-Clause
  license_file: LICENSE
  summary: QuantEcon is a package to support all forms of quantitative economic modelling.
  description: |
    **QuantEcon** is an organization run by economists for economists with the aim of coordinating
    distributed development of high quality open source code for all forms of quantitative economic modelling.
    The project website is located at [http://quantecon.org/](http://quantecon.org/). This website provides
    more information with regards to the **quantecon** library, documentation, in addition to some resources
    in regards to how you can use and/or contribute to the package.

    The [repository](https://github.com/QuantEcon/QuantEcon.py>) includes the *conda-forge* build recipe for the *quantecon* python package.

    **Note:** There is also a Julia version available for Julia users [QuantEcon.jl](https://github.com/QuantEcon/QuantEcon.jl)
  doc_url: http://quanteconpy.readthedocs.io/en/latest/
  dev_url: https://github.com/QuantEcon/QuantEcon.py

extra:
  recipe-maintainers:
    - knaaptime
    - mmcky
    - jstac
