{% set version = "0.5.3" %}
{% set sha256 = "279f94ddae910aaecaa5ed5b34affb8400d5836f37aff212adce53797edf5013" %}

package:
  name: quantecon
  version: {{ version }}

source:
  fn: QuantEcon.py-{{ version }}.tar.gz
  url: https://github.com/QuantEcon/QuantEcon.py/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<35]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - flit
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - sympy
    - numba
    - requests
    - nose
    - pytables


test:
  imports:
    - quantecon
    - quantecon.tests
    - quantecon.game_theory
    - quantecon.markov
    - quantecon.random
    - quantecon.util

about:
  home: https://github.com/QuantEcon/QuantEcon.py
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: QuantEcon is a package to support all forms of quantitative economic modelling.
  description: |
    **QuantEcon** is an organization run by economists for economists with the aim of coordinating
    distributed development of high quality open source code for all forms of quantitative economic modelling.
    The project website is located at [http://quantecon.org/](http://quantecon.org/). This website provides
    more information with regards to the **quantecon** library, documentation, in addition to some resources
    in regards to how you can use and/or contribute to the package.

    The [repository](https://github.com/QuantEcon/QuantEcon.py>) includes the *conda-forge* build recipe for the *quantecon* python package.

    **Note:** There is also a Julia version available for Julia users [QuantEcon.jl](https://github.com/QuantEcon/QuantEcon.jl)
  doc_url: http://quanteconpy.readthedocs.io/en/latest/
  dev_url: https://github.com/QuantEcon/QuantEcon.py

extra:
  recipe-maintainers:
    - mmcky
    - jstac
