{% set name = "quantecon" %}
{% set version = "0.5.3" %}

package:
  name: quantecon
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quantecon-{{ version }}.tar.gz
  sha256: ff9f4378069ff5713d3d8ce8efaa123b24910cb1a2eb69b4bba4735ff08f2768

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python >=3.7
    - flit-core >=3.5,<4
  run:
    - numba
    - numpy
    - python >=3.7
    - requests
    - scipy >=1.0.0
    - sympy

test:
  imports:
    - quantecon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QuantEcon/QuantEcon.py
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: QuantEcon is a package to support all forms of quantitative economic modelling.
  description: |
    **QuantEcon** is an organization run by economists for economists with the aim of coordinating
    distributed development of high quality open source code for all forms of quantitative economic modelling.
    The project website is located at [http://quantecon.org/](http://quantecon.org/). This website provides
    more information with regards to the **quantecon** library, documentation, in addition to some resources
    in regards to how you can use and/or contribute to the package.

    The [repository](https://github.com/QuantEcon/QuantEcon.py>) includes the *conda-forge* build recipe for the *quantecon* python package.

    **Note:** There is also a Julia version available for Julia users [QuantEcon.jl](https://github.com/QuantEcon/QuantEcon.jl)
  doc_url: http://quanteconpy.readthedocs.io/en/latest/
  dev_url: https://github.com/QuantEcon/QuantEcon.py

extra:
  recipe-maintainers:
    - mmcky
    - jstac
